IF TYPE_ID(N'dbo.tvp_wms_inventario_regularizacion_mov_v1') IS NULL
BEGIN
    EXEC('CREATE TYPE dbo.tvp_wms_inventario_regularizacion_mov_v1 AS TABLE (
        RowId INT NOT NULL,
        IdEmpresa INT NOT NULL,
        IdBodegaOrigen INT NOT NULL,
        IdTransaccion INT NOT NULL,
        IdPropietarioBodega INT NULL,
        IdProductoBodega INT NULL,
        IdUbicacionOrigen INT NULL,
        IdUbicacionDestino INT NULL,
        IdPresentacion INT NULL,
        IdEstadoOrigen INT NULL,
        IdEstadoDestino INT NULL,
        IdUnidadMedida INT NULL,
        IdTipoTarea INT NULL,
        IdBodegaDestino INT NULL,
        IdRecepcion INT NULL,
        cantidad FLOAT NULL,
        serie NVARCHAR(200) NULL,
        peso FLOAT NULL,
        lote NVARCHAR(200) NULL,
        fecha_vence DATETIME NULL,
        fecha DATETIME NULL,
        barra_pallet NVARCHAR(200) NULL,
        hora_ini DATETIME NULL,
        hora_fin DATETIME NULL,
        fecha_agr DATETIME NULL,
        usuario_agr NVARCHAR(200) NULL,
        cantidad_hist FLOAT NULL,
        peso_hist FLOAT NULL,
        IdOperadorBodega INT NULL,
        lic_plate NVARCHAR(200) NULL,
        IdRecepcionDet INT NULL,
        IdPedidoEnc INT NULL,
        IdPedidoDet INT NULL,
        IdDespachoEnc INT NULL,
        IdDespachoDet INT NULL,
        IdProductoTallaColor INT NULL,
        Talla NVARCHAR(100) NULL,
        Color NVARCHAR(100) NULL,
        PRIMARY KEY (RowId)
    )')
END
GO
